<#include "CommonUtil.ftl"/>

    <link rel="stylesheet" href="${ctx}/r/cms/www/red/css/zrqd.css"/>

<div class="con_top">
    <h2>“双公示”工作责任人员名单</h2>
    <div class="con_top_shu">
        <ul>
            <li class="li_first">
                <span>单位</span>
                <span></span>
                <span>姓名</span>
                <span>职务</span>
                <span>联系电话（手机）</span>
            </li>
            <li>
                <span>公安局</span>
                <span>
                                <a>负责人</a>
                                <a>联络人</a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
            </li>
            <li>
                <span>工商局</span>
                <span>
                                <a>负责人</a>
                                <a>联络人</a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
                <span>
                                <a></a>
                                <a></a>
                            </span>
            </li>
            <li>
                <span>人社局</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>财政局</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>住建局</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>法院</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>监察局</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>检查局</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>文明办</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
            <li>
                <span>发改委</span>
                <span>
                                    <a>负责人</a>
                                    <a>联络人</a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
                <span>
                                    <a></a>
                                    <a></a>
                                </span>
            </li>
        </ul>
    </div>
</div>

<!--</div>-->
<!--</div>-->

<#--</body>-->
<#--</html>-->
